name: Swells For Kings
favicon: null
layout_spectrum: 1
typography_spectrum: 0.93359
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4c6569'
    - '#d1d6dc'
    - '#a5afbb'
    - '#000706'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
