favicon: null
name: Swells For Kings
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.561366368085146
  brandStrength: 0.7807646
  lightness: 0.8626611747313291
  brandColors:
    - '#030305'
    - '#F2E0C7'
    - '#A29990'
    - '#FFB54B'
    - '#A3401E'
  rhythmicContrast: 0.8912409362383187
typography_spectrum: 0.8990442
layout_spectrum: 0.9181601
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
