name: Swells For Kings
favicon: null
layout_spectrum: 0.49426881526596844
typography_spectrum: 0.7123064135666937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.914070759434253
  lightness: 0.8626611747313291
  saturation: 0.561366368085146
  rhythmicContrast: 0.8912409362383187
purpose: []
