name: Swells For Kings
favicon: null
layout_spectrum: 0
typography_spectrum: 0.93359
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#F2E0C7'
    - '#A29990'
    - '#FFB54B'
    - '#A3401E'
  brandStrength: 0.8125
  lightness: 0.8626611747313291
  saturation: 0.561366368085146
  rhythmicContrast: 0.8912409362383187
purpose: []
